### ISSUE TITLE
Potential Errors in Evaluation script

### ISSUE THREAD

**Issue by Jiaqi-Lv** [computationalpathologygroup/monkey-challenge#1]
I have noticed two potential errors in your evaluation script. They are in the `match_coordinates()` function.
https://github.com/computationalpathologygroup/monkey-challenge/blob/c29b5d7d0e3e8f63c3a092b76df822111c8497cf/evaluation/evaluate.py#L163

The first error is here https://github.com/computationalpathologygroup/monkey-challenge/blob/c29b5d7d0e3e8f63c3a092b76df822111c8497cf/evaluation/evaluate.py#L181
`if len(ground_truth) == 0 or len(predictions) == 0:
        return 0, 0, 0, np.array([]), np.array([])`
If there are no ground truth, but there are predictions, the number false positives shouldn't be zero.
I would suggest changing `or ` to `and` here.

The second error is here https://github.com/computationalpathologygroup/monkey-challenge/blob/c29b5d7d0e3e8f63c3a092b76df822111c8497cf/evaluation/evaluate.py#L197
In this loop, if a matching coordinate has been found, it should be removed from the predictions. Otherwise the same predicted coordinate could be matched to more than one ground truth. If this happens you will get more `matched_gt` than the actual number of predictions, this will lead to the number of false positives being negative. A fix can be setting the distance of the matched coordinate to all other ground truth coordinates to infinity, which prevents it to be matched again: `dist_matrix[:, closest_pred_idx] = np.inf`

**Comment by LindaSt** [comment]
This has been fixed in commit c835da2569462b0f47426d38d5e860e35310eab0 and e027e23cee3fb23ea697c264f3ed0b73e0336f34.
